site_name: Immersion Kit Docs
theme:
  name: material
  palette: 
    - scheme: slate 
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences